Manufacturing-refactor-move-to-livestacks-repo (#78)
* build-plan update

* big-star-retail-ai-agent container

Hosts compose files to spin up locally on any environment.

* update big-star-retial

* Created .env.example

* livelabs-livestack-big-star-retail-screenshots-update

* some code changes in the stack.

some code changes in the stack.

* Changes to Compose yml and stack.

* main.py changes

In main.py:324, the / route was using the old template API:

  return templates.TemplateResponse("index.html", {"request": request})

  With the FastAPI/Starlette version in this container, TemplateResponse now expects:

  TemplateResponse(request, name, context=...)

  So the old call was effectively passing the context dict where the template name should go, which caused:

  TypeError: unhashable type: 'dict'

  I changed it to:

  return templates.TemplateResponse(request, "index.html")

  That’s what removed the 500 Internal Server Error on GET /. Nothing in the database, ORDS, or Ollama stack was changed.

* Seer Sporting Goods LiveStack WMS ID: 12050

* resized images

resized images

* html patch

* update ll-demo-agent LiveStack markdown

* Adding Windows Powershell Commands

* Minor change

* social-commerce-the-tim-app-livestack-and-guide

* Oracle Augmented Card Authorisation App

* Updated image sizes

* Updated naming

* oracle-augmented-bank updates to match new screenshots

* resized images

* Updated Seer Equities story

* port reference updates in documents.

* Finance Edition LiveStack Runbook

* Update image sizes

* PAR URL included

* Healthcare Runbook

* healthcare runbook update

* Utilities Runbook

* media-runbook update

* Media runbook.

* manufacturing and media runbook updates

* utilities-runbook-update

* media-utilities-runbook-updates

* take-it-home-for-runbooks-add

* updated manifest media

* all stack manifest upload and download livestack lab included

* manufacturing-runbook

* hightech-runbook

* state and local government runbook

* manufacturing-runbook-update

* Manufacturing-LiveStack-Demo-In-LiveStacks-Repo